fn main() {
    println!("Hola soy un mensaje de la linea 2");

    println!("Hola soy un mensaje de la linea 4");
    // en rust no existen los errores ni las excepciones, solo panic!
    panic!("el programa finaliza de forma inesperada");

    println!("Hola soy un mensaje de la linea 6");

    println!("Hola soy un mensaje de la linea 8");

}
